name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      # NOTE: We intentionally lint against our minimum supported Python.
      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: "3.7"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: deps
        run: make dev EXTRA=lint

      - name: lint
        run: make lint