name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      # NOTE: We intentionally lint against our minimum supported Python.
      - uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
        with:
          python-version: "3.7"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: deps
        run: make dev EXTRA=lint

      - name: lint
        run: make lint