name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      # NOTE: We intentionally lint against our minimum supported Python.
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: "3.7"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: deps
        run: make dev EXTRA=lint

      - name: lint
        run: make lint